version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - setup_remote_docker
          reusable: true    # default - false
      - run: |
          make all
